# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a3a7aa7a95a62e5b57149d20d57c5ed3b4f6c5f4ae2c48368f79185c4b71a97bbc52f5c8a9177b51def8dd48e63af6d785df94c122c543aecefa9ce09c0414

test:
  secret_key_base: 6bd7e5153b12937c7cf571f16a7b8fe9a8721f8cefd2e5c59a7ea3b30c92362d3913b8a0d86884cfbc680b55c4bb61a1b2df8d2ee4dfe764c7bbd5cd35ca02c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
